title: Automatiseringen
id: automations
icon: mdi:settings
cards:
  - type: entities
    show_header_toggle: false
    title: Automatiseringen
    entities:
      - entity: automation.turn_lights_on_when_sun_sets
        name: Lichten aan bij zonsondergang
      - entity: automation.turn_lights_off_during_week_days
        name: Lichten uit - weekdagen
      - entity: automation.turn_lights_off_during_weekend
        name: Lichten uit - weekend
