- id: '1588960128724'
  alias: Turn lights on when sun sets
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  action:
    service: switch.turn_on
    entity_id: switch.living

- alias: Turn lights off during week days
  trigger:
    platform: time
    at: "22:59:00"
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ now().weekday() < 4 }}'
      - condition: state
        entity_id: automation.turn_lights_off_during_weekend
        state: 'off'
  action:
    entity_id: switch.living
    service: switch.turn_off

- alias: Turn lights off during weekend
  trigger:
    platform: time
    at: "23:59:00"
  condition:
    - condition: template
      value_template: '{{ now().weekday() > 3 }}'
  action:
    - service: switch.turn_off
      entity_id: switch.living
    - service: notify.mobile_app_hd1913
      data_template:
        title: "Weekend lights off"
        message: "Event triggered has been triggered with following value: {{ now().weekday() }}"