# shadow: false
# compact_mode: true
# hide_unused: true

# show_tabs: 'Home, bedroom'
# hidden_tab_redirect: false
# tab_container_css: 'max-width: 1425px !important; margin: 0 auto !important;'
# all_tabs_css: "width: 35px !important;"