sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: disk_use_percent
        arg: /home
      - type: disk_free
        arg: /home
      - type: memory_free
      - type: last_boot
      - type: ipv4_address